/***********************************************************************
!!!!!! DO NOT MODIFY !!!!!!

GacGen.exe Resource.xml

This file is generated by Workflow compiler
https://github.com/vczh-libraries
***********************************************************************/

#include "PunkUI.h"
/* CodePack:BeginIgnore() */
#ifndef VCZH_DEBUG_NO_REFLECTION
/* CodePack:ConditionOff(VCZH_DEBUG_NO_REFLECTION, PunkUIReflection.h) */
#include "PunkUIReflection.h"
#endif
/* CodePack:EndIgnore() */

#if defined( _MSC_VER)
#pragma warning(push)
#pragma warning(disable:4250)
#elif defined(__clang__)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wparentheses-equality"
#elif defined(__GNUC__)
#pragma GCC diagnostic push
#endif

#define GLOBAL_SYMBOL ::vl_workflow_global::PunkUI::
#define GLOBAL_NAME ::vl_workflow_global::PunkUI::Instance().
#define GLOBAL_OBJ &::vl_workflow_global::PunkUI::Instance()

/* USER_CONTENT_BEGIN(custom global declarations) */
#include "../../PunkElements/PunkFx.h"
/* USER_CONTENT_END() */

/***********************************************************************
Class (::punkui::DangerButtonTemplate)
***********************************************************************/

namespace punkui
{
	void DangerButtonTemplate::InitFx()
	{/* USER_CONTENT_BEGIN(::punkui::DangerButtonTemplate) */
		auto liftFx = punkfx::GetFxSlot<punkfx::LiftDriver>(this, L"PunkFx.Lift");
		liftFx->Bind(this->lift);
		::vl::__vwsn::EventAttach(this->StateChanged, ::vl::Func<void(::vl::presentation::compositions::GuiGraphicsComposition*, ::vl::presentation::compositions::GuiEventArgs*)>(
			[this, liftFx](::vl::presentation::compositions::GuiGraphicsComposition* sender, ::vl::presentation::compositions::GuiEventArgs* arguments)
			{
				liftFx->OnStateChanged(this->GetState(), this);
			}));
		// 皮肤按钮命中模板内部组合时 eventSource != boundsComposition，
		// GuiButton::OnMouseEnter/OnMouseDown 会把 hover/Pressed 全部过滤掉。
		// 组合级 mouseEnter/mouseLeave 按 hit 链派发给祖先组合，无此过滤：
		// 首次进入时（此时宿主必已挂树）打开控件层透传，并把 hover 信号直送给 lift
		this->lift->GetEventReceiver()->mouseEnter.AttachLambda([this, liftFx](::vl::presentation::compositions::GuiGraphicsComposition* sender, ::vl::presentation::compositions::GuiEventArgs& arguments)
		{
			if (auto owner = dynamic_cast<::vl::presentation::controls::GuiButton*>(this->GetRelatedControl()))
			{
				owner->SetIgnoreChildControlMouseEvents(false);
			}
			liftFx->SetHover(true, this);
		});
		this->lift->GetEventReceiver()->mouseLeave.AttachLambda([this, liftFx](::vl::presentation::compositions::GuiGraphicsComposition* sender, ::vl::presentation::compositions::GuiEventArgs& arguments)
		{
			liftFx->SetHover(false, this);
		});
	}/* USER_CONTENT_END() */

	DangerButtonTemplate::DangerButtonTemplate()
	{
		auto __vwsn_resource_ = ::vl::__vwsn::This(::vl::presentation::GetResourceManager())->GetResourceFromClassName(::vl::WString::Unmanaged(L"punkui::DangerButtonTemplate"));
		auto __vwsn_resolver_ = ::vl::Ptr<::vl::presentation::GuiResourcePathResolver>(new ::vl::presentation::GuiResourcePathResolver(__vwsn_resource_, ::vl::__vwsn::This(__vwsn_resource_.Obj())->GetWorkingDirectory()));
		::vl::__vwsn::This(this)->SetResourceResolver(__vwsn_resolver_);
		::vl::__vwsn::This(this)->__vwsn_punkui_DangerButtonTemplate_Initialize(this);
		this->__vwsn_instance_ctor_();
	}

	void DangerButtonTemplate::__vwsn_instance_ctor_()
	{
		::vl::__vwsn::This(this->self)->InitFx();
	}

	DangerButtonTemplate::~DangerButtonTemplate()
	{
		this->FinalizeInstanceRecursively(static_cast<::vl::presentation::templates::GuiTemplate*>(this));
	}

}
#undef GLOBAL_SYMBOL
#undef GLOBAL_NAME
#undef GLOBAL_OBJ

#if defined( _MSC_VER)
#pragma warning(pop)
#elif defined(__clang__)
#pragma clang diagnostic pop
#elif defined(__GNUC__)
#pragma GCC diagnostic pop
#endif
