/***********************************************************************
!!!!!! DO NOT MODIFY !!!!!!

GacGen.exe Resource.xml

This file is generated by Workflow compiler
https://github.com/vczh-libraries
***********************************************************************/

#ifndef VCZH_WORKFLOW_COMPILER_GENERATED_DANGERBUTTONTEMPLATE
#define VCZH_WORKFLOW_COMPILER_GENERATED_DANGERBUTTONTEMPLATE

#include "PunkUIPartialClasses.h"

#if defined( _MSC_VER)
#pragma warning(push)
#pragma warning(disable:4250)
#elif defined(__clang__)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wparentheses-equality"
#elif defined(__GNUC__)
#pragma GCC diagnostic push
#endif

namespace punkui
{
	class DangerButtonTemplate : public ::vl::presentation::templates::GuiButtonTemplate, public ::punkui::DangerButtonTemplateConstructor, public ::vl::reflection::Description<DangerButtonTemplate>
	{
		friend class ::punkui::DangerButtonTemplateConstructor;
		friend class ::vl_workflow_global::__vwsnc1_PunkUI_punkui_DangerButtonTemplateConstructor___vwsn_punkui_DangerButtonTemplate_Initialize__vl_reflection_description_IValueSubscription;
		friend class ::vl_workflow_global::__vwsnc2_PunkUI_punkui_DangerButtonTemplateConstructor___vwsn_punkui_DangerButtonTemplate_Initialize__vl_reflection_description_IValueSubscription;
		friend class ::vl_workflow_global::__vwsnc3_PunkUI_punkui_DangerButtonTemplateConstructor___vwsn_punkui_DangerButtonTemplate_Initialize__vl_reflection_description_IValueSubscription;
		friend struct ::vl_workflow_global::__vwsnf22_PunkUI_punkui_DangerButtonTemplateConstructor___vwsn_punkui_DangerButtonTemplate_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf23_PunkUI_punkui_DangerButtonTemplateConstructor___vwsn_punkui_DangerButtonTemplate_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf24_PunkUI_punkui_DangerButtonTemplateConstructor___vwsn_punkui_DangerButtonTemplate_Initialize_;
#ifdef VCZH_DESCRIPTABLEOBJECT_WITH_METADATA
		friend struct ::vl::reflection::description::CustomTypeDescriptorSelector<DangerButtonTemplate>;
#endif
	private:
		void InitFx();
	public:
		DangerButtonTemplate();
		void __vwsn_instance_ctor_();
		~DangerButtonTemplate();

	/* USER_CONTENT_BEGIN(custom members of ::punkui::DangerButtonTemplate) */
	/* USER_CONTENT_END() */
	};

}
#if defined( _MSC_VER)
#pragma warning(pop)
#elif defined(__clang__)
#pragma clang diagnostic pop
#elif defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

#endif
