/***********************************************************************
!!!!!! DO NOT MODIFY !!!!!!

GacGen.exe Resource.xml

This file is generated by Workflow compiler
https://github.com/vczh-libraries
***********************************************************************/

#ifndef VCZH_WORKFLOW_COMPILER_GENERATED_DASHBOARDPAGETEMPLATE
#define VCZH_WORKFLOW_COMPILER_GENERATED_DASHBOARDPAGETEMPLATE

#include "PunkUIPartialClasses.h"

#if defined( _MSC_VER)
#pragma warning(push)
#pragma warning(disable:4250)
#elif defined(__clang__)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wparentheses-equality"
#elif defined(__GNUC__)
#pragma GCC diagnostic push
#endif

namespace punkui
{
	class DashboardPageTemplate : public ::vl::presentation::templates::GuiControlTemplate, public ::punkui::DashboardPageTemplateConstructor, public ::vl::reflection::Description<DashboardPageTemplate>
	{
		friend class ::punkui::DashboardPageTemplateConstructor;
		friend struct ::vl_workflow_global::__vwsnf13_PunkUI_punkui_DashboardPageTemplateConstructor___vwsn_punkui_DashboardPageTemplate_Initialize_;
#ifdef VCZH_DESCRIPTABLEOBJECT_WITH_METADATA
		friend struct ::vl::reflection::description::CustomTypeDescriptorSelector<DashboardPageTemplate>;
#endif
	private:
		void InstallPunkPanels();
	public:
		DashboardPageTemplate();
		void __vwsn_instance_ctor_();
		~DashboardPageTemplate();

	/* USER_CONTENT_BEGIN(custom members of ::punkui::DashboardPageTemplate) */
	/* USER_CONTENT_END() */
	};

}
#if defined( _MSC_VER)
#pragma warning(pop)
#elif defined(__clang__)
#pragma clang diagnostic pop
#elif defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

#endif
