/***********************************************************************
!!!!!! DO NOT MODIFY !!!!!!

GacGen.exe Resource.xml

This file is generated by Workflow compiler
https://github.com/vczh-libraries
***********************************************************************/

#include "PunkUI.h"
/* CodePack:BeginIgnore() */
#ifndef VCZH_DEBUG_NO_REFLECTION
/* CodePack:ConditionOff(VCZH_DEBUG_NO_REFLECTION, PunkUIReflection.h) */
#include "PunkUIReflection.h"
#endif
/* CodePack:EndIgnore() */

#if defined( _MSC_VER)
#pragma warning(push)
#pragma warning(disable:4250)
#elif defined(__clang__)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wparentheses-equality"
#elif defined(__GNUC__)
#pragma GCC diagnostic push
#endif

#define GLOBAL_SYMBOL ::vl_workflow_global::PunkUI::
#define GLOBAL_NAME ::vl_workflow_global::PunkUI::Instance().
#define GLOBAL_OBJ &::vl_workflow_global::PunkUI::Instance()

/* USER_CONTENT_BEGIN(custom global declarations) */
namespace punkui {
	static void AttachDashPanel(const PunkPanelStyle& style, GuiBoundsComposition* face)
	{
		static PunkPanel* panels[32] = {};
		static int next = 0;
		if (next < 32)
		{
			panels[next] = new PunkPanel(style);
			panels[next]->AttachTo(face);
			next++;
		}
	}
}
/* USER_CONTENT_END() */

/***********************************************************************
Class (::punkui::DashboardPageTemplate)
***********************************************************************/

namespace punkui
{
	void DashboardPageTemplate::InstallPunkPanels()
	{/* USER_CONTENT_BEGIN(::punkui::DashboardPageTemplate) */
		AttachDashPanel(PunkPanelStyle::Card(), dashMainFace);
		AttachDashPanel(PunkPanelStyle::Card(), dashStatusFace);
		AttachDashPanel(PunkPanelStyle::Card(), dashEventsFace);
		AttachDashPanel(PunkPanelStyle::Bar(), bar1Face);
		AttachDashPanel(PunkPanelStyle::Bar(), bar2Face);
		AttachDashPanel(PunkPanelStyle::Bar(), bar3Face);
		AttachDashPanel(PunkPanelStyle::Bar(), bar4Face);
		AttachDashPanel(PunkPanelStyle::Bar(), bar5Face);
		AttachDashPanel(PunkPanelStyle::Bar(), bar6Face);
		AttachDashPanel(PunkPanelStyle::Bar(), bar7Face);
		AttachDashPanel(PunkPanelStyle::Bar(), bar8Face);
		AttachDashPanel(PunkPanelStyle::Bar(), bar9Face);
		AttachDashPanel(PunkPanelStyle::Bar(), bar10Face);
		AttachDashPanel(PunkPanelStyle::Bar(), bar11Face);
		AttachDashPanel(PunkPanelStyle::Bar(), bar12Face);
	}/* USER_CONTENT_END() */

	DashboardPageTemplate::DashboardPageTemplate()
	{
		auto __vwsn_resource_ = ::vl::__vwsn::This(::vl::presentation::GetResourceManager())->GetResourceFromClassName(::vl::WString::Unmanaged(L"punkui::DashboardPageTemplate"));
		auto __vwsn_resolver_ = ::vl::Ptr<::vl::presentation::GuiResourcePathResolver>(new ::vl::presentation::GuiResourcePathResolver(__vwsn_resource_, ::vl::__vwsn::This(__vwsn_resource_.Obj())->GetWorkingDirectory()));
		::vl::__vwsn::This(this)->SetResourceResolver(__vwsn_resolver_);
		::vl::__vwsn::This(this)->__vwsn_punkui_DashboardPageTemplate_Initialize(this);
		this->__vwsn_instance_ctor_();
	}

	void DashboardPageTemplate::__vwsn_instance_ctor_()
	{
		::vl::__vwsn::This(this->page)->InstallPunkPanels();
	}

	DashboardPageTemplate::~DashboardPageTemplate()
	{
		this->FinalizeInstanceRecursively(static_cast<::vl::presentation::templates::GuiTemplate*>(this));
	}

}
#undef GLOBAL_SYMBOL
#undef GLOBAL_NAME
#undef GLOBAL_OBJ

#if defined( _MSC_VER)
#pragma warning(pop)
#elif defined(__clang__)
#pragma clang diagnostic pop
#elif defined(__GNUC__)
#pragma GCC diagnostic pop
#endif
