/***********************************************************************
!!!!!! DO NOT MODIFY !!!!!!

GacGen.exe Resource.xml

This file is generated by Workflow compiler
https://github.com/vczh-libraries
***********************************************************************/

#ifndef VCZH_WORKFLOW_COMPILER_GENERATED_GHOSTBUTTONTEMPLATE
#define VCZH_WORKFLOW_COMPILER_GENERATED_GHOSTBUTTONTEMPLATE

#include "PunkUIPartialClasses.h"

#if defined( _MSC_VER)
#pragma warning(push)
#pragma warning(disable:4250)
#elif defined(__clang__)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wparentheses-equality"
#elif defined(__GNUC__)
#pragma GCC diagnostic push
#endif

namespace punkui
{
	class GhostButtonTemplate : public ::vl::presentation::templates::GuiButtonTemplate, public ::punkui::GhostButtonTemplateConstructor, public ::vl::reflection::Description<GhostButtonTemplate>
	{
		friend class ::punkui::GhostButtonTemplateConstructor;
		friend class ::vl_workflow_global::__vwsnc4_PunkUI_punkui_GhostButtonTemplateConstructor___vwsn_punkui_GhostButtonTemplate_Initialize__vl_reflection_description_IValueSubscription;
		friend class ::vl_workflow_global::__vwsnc5_PunkUI_punkui_GhostButtonTemplateConstructor___vwsn_punkui_GhostButtonTemplate_Initialize__vl_reflection_description_IValueSubscription;
		friend class ::vl_workflow_global::__vwsnc6_PunkUI_punkui_GhostButtonTemplateConstructor___vwsn_punkui_GhostButtonTemplate_Initialize__vl_reflection_description_IValueSubscription;
		friend struct ::vl_workflow_global::__vwsnf25_PunkUI_punkui_GhostButtonTemplateConstructor___vwsn_punkui_GhostButtonTemplate_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf26_PunkUI_punkui_GhostButtonTemplateConstructor___vwsn_punkui_GhostButtonTemplate_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf27_PunkUI_punkui_GhostButtonTemplateConstructor___vwsn_punkui_GhostButtonTemplate_Initialize_;
#ifdef VCZH_DESCRIPTABLEOBJECT_WITH_METADATA
		friend struct ::vl::reflection::description::CustomTypeDescriptorSelector<GhostButtonTemplate>;
#endif
	private:
		void InitFx();
	public:
		GhostButtonTemplate();
		void __vwsn_instance_ctor_();
		~GhostButtonTemplate();

	/* USER_CONTENT_BEGIN(custom members of ::punkui::GhostButtonTemplate) */
	/* USER_CONTENT_END() */
	};

}
#if defined( _MSC_VER)
#pragma warning(pop)
#elif defined(__clang__)
#pragma clang diagnostic pop
#elif defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

#endif
