/***********************************************************************
!!!!!! DO NOT MODIFY !!!!!!

GacGen.exe Resource.xml

This file is generated by Workflow compiler
https://github.com/vczh-libraries
***********************************************************************/

#include "PunkUI.h"
/* CodePack:BeginIgnore() */
#ifndef VCZH_DEBUG_NO_REFLECTION
/* CodePack:ConditionOff(VCZH_DEBUG_NO_REFLECTION, PunkUIReflection.h) */
#include "PunkUIReflection.h"
#endif
/* CodePack:EndIgnore() */

#if defined( _MSC_VER)
#pragma warning(push)
#pragma warning(disable:4250)
#elif defined(__clang__)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wparentheses-equality"
#elif defined(__GNUC__)
#pragma GCC diagnostic push
#endif

#define GLOBAL_SYMBOL ::vl_workflow_global::PunkUI::
#define GLOBAL_NAME ::vl_workflow_global::PunkUI::Instance().
#define GLOBAL_OBJ &::vl_workflow_global::PunkUI::Instance()

/* USER_CONTENT_BEGIN(custom global declarations) */
namespace punkui { namespace mainpanels {
	static PunkPanel bgPanel(PunkPanelStyle::WindowBg());
	static PunkPanel navShowcasePanel(PunkPanelStyle::Nav());
	static PunkPanel navDashboardPanel(PunkPanelStyle::Nav());
	static PunkPanel modalPanel(PunkPanelStyle::Card());
}}
/* USER_CONTENT_END() */

/***********************************************************************
Class (::punkui::MainWindow)
***********************************************************************/

namespace punkui
{
	void MainWindow::InstallPunkPanels()
	{/* USER_CONTENT_BEGIN(::punkui::MainWindow) */
		mainpanels::bgPanel.AttachTo(bgHalftone);
		mainpanels::navShowcasePanel.AttachTo(navShowcaseFace);
		mainpanels::navDashboardPanel.AttachTo(navDashboardFace);
		mainpanels::modalPanel.AttachTo(modalFace);
		SetNavActive(0);
	}/* USER_CONTENT_END() */

	void MainWindow::SetNavActive(::vl::vint64_t index)
	{/* USER_CONTENT_BEGIN(::punkui::MainWindow) */
		bool showCase = index == 0;
		showcasePage->SetVisible(showCase);
		dashboardPage->SetVisible(!showCase);

		PunkPanelStyle active = PunkPanelStyle::Nav();
		PunkPanelStyle inactive = active;
		inactive.background = Color(0, 0, 0, 0);
		inactive.borderWidth = 0;
		inactive.shadowOffset = 0;

		mainpanels::navShowcasePanel.UpdateStyle(showCase ? active : inactive);
		mainpanels::navDashboardPanel.UpdateStyle(showCase ? inactive : active);
		mainpanels::navShowcasePanel.RequestRender(this);
		mainpanels::navDashboardPanel.RequestRender(this);
	}/* USER_CONTENT_END() */

	void MainWindow::OpenModal()
	{/* USER_CONTENT_BEGIN(::punkui::MainWindow) */
		modalOverlay->SetVisible(true);
	}/* USER_CONTENT_END() */

	MainWindow::MainWindow()
		: ::vl::presentation::controls::GuiWindow(::vl::presentation::theme::ThemeName::Window)
	{
		auto __vwsn_resource_ = ::vl::__vwsn::This(::vl::presentation::GetResourceManager())->GetResourceFromClassName(::vl::WString::Unmanaged(L"punkui::MainWindow"));
		auto __vwsn_resolver_ = ::vl::Ptr<::vl::presentation::GuiResourcePathResolver>(new ::vl::presentation::GuiResourcePathResolver(__vwsn_resource_, ::vl::__vwsn::This(__vwsn_resource_.Obj())->GetWorkingDirectory()));
		::vl::__vwsn::This(this)->SetResourceResolver(__vwsn_resolver_);
		::vl::__vwsn::This(this)->__vwsn_punkui_MainWindow_Initialize(this);
		this->__vwsn_instance_ctor_();
	}

	void MainWindow::__vwsn_instance_ctor_()
	{
		::vl::__vwsn::This(this->root)->InstallPunkPanels();
	}

	MainWindow::~MainWindow()
	{
		this->FinalizeInstanceRecursively(static_cast<::vl::presentation::controls::GuiControlHost*>(this));
	}

}
#undef GLOBAL_SYMBOL
#undef GLOBAL_NAME
#undef GLOBAL_OBJ

#if defined( _MSC_VER)
#pragma warning(pop)
#elif defined(__clang__)
#pragma clang diagnostic pop
#elif defined(__GNUC__)
#pragma GCC diagnostic pop
#endif
