/***********************************************************************
!!!!!! DO NOT MODIFY !!!!!!

GacGen.exe Resource.xml

This file is generated by Workflow compiler
https://github.com/vczh-libraries
***********************************************************************/

#ifndef VCZH_WORKFLOW_COMPILER_GENERATED_MAINWINDOW
#define VCZH_WORKFLOW_COMPILER_GENERATED_MAINWINDOW

#include "PunkUIPartialClasses.h"

#if defined( _MSC_VER)
#pragma warning(push)
#pragma warning(disable:4250)
#elif defined(__clang__)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wparentheses-equality"
#elif defined(__GNUC__)
#pragma GCC diagnostic push
#endif

namespace punkui
{
	class MainWindow : public ::vl::presentation::controls::GuiWindow, public ::punkui::MainWindowConstructor, public ::vl::reflection::Description<MainWindow>
	{
		friend class ::punkui::MainWindowConstructor;
		friend struct ::vl_workflow_global::__vwsnf10_PunkUI_punkui_MainWindowConstructor___vwsn_punkui_MainWindow_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf1_PunkUI_punkui_MainWindowConstructor___vwsn_punkui_MainWindow_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf2_PunkUI_punkui_MainWindowConstructor___vwsn_punkui_MainWindow_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf3_PunkUI_punkui_MainWindowConstructor___vwsn_punkui_MainWindow_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf4_PunkUI_punkui_MainWindowConstructor___vwsn_punkui_MainWindow_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf5_PunkUI_punkui_MainWindowConstructor___vwsn_punkui_MainWindow_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf6_PunkUI_punkui_MainWindowConstructor___vwsn_punkui_MainWindow_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf7_PunkUI_punkui_MainWindowConstructor___vwsn_punkui_MainWindow_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf8_PunkUI_punkui_MainWindowConstructor___vwsn_punkui_MainWindow_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf9_PunkUI_punkui_MainWindowConstructor___vwsn_punkui_MainWindow_Initialize_;
#ifdef VCZH_DESCRIPTABLEOBJECT_WITH_METADATA
		friend struct ::vl::reflection::description::CustomTypeDescriptorSelector<MainWindow>;
#endif
	private:
		void InstallPunkPanels();
		void SetNavActive(::vl::vint64_t index);
	public:
		void OpenModal();
		MainWindow();
		void __vwsn_instance_ctor_();
		~MainWindow();

	/* USER_CONTENT_BEGIN(custom members of ::punkui::MainWindow) */
	/* USER_CONTENT_END() */
	};

}
#if defined( _MSC_VER)
#pragma warning(pop)
#elif defined(__clang__)
#pragma clang diagnostic pop
#elif defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

#endif
