/***********************************************************************
!!!!!! DO NOT MODIFY !!!!!!

GacGen.exe Resource.xml

This file is generated by Workflow compiler
https://github.com/vczh-libraries
***********************************************************************/

#ifndef VCZH_WORKFLOW_COMPILER_GENERATED_OUTLINEBUTTONTEMPLATE
#define VCZH_WORKFLOW_COMPILER_GENERATED_OUTLINEBUTTONTEMPLATE

#include "PunkUIPartialClasses.h"

#if defined( _MSC_VER)
#pragma warning(push)
#pragma warning(disable:4250)
#elif defined(__clang__)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wparentheses-equality"
#elif defined(__GNUC__)
#pragma GCC diagnostic push
#endif

namespace punkui
{
	class OutlineButtonTemplate : public ::vl::presentation::templates::GuiButtonTemplate, public ::punkui::OutlineButtonTemplateConstructor, public ::vl::reflection::Description<OutlineButtonTemplate>
	{
		friend class ::punkui::OutlineButtonTemplateConstructor;
		friend class ::vl_workflow_global::__vwsnc10_PunkUI_punkui_OutlineButtonTemplateConstructor___vwsn_punkui_OutlineButtonTemplate_Initialize__vl_reflection_description_IValueSubscription;
		friend class ::vl_workflow_global::__vwsnc8_PunkUI_punkui_OutlineButtonTemplateConstructor___vwsn_punkui_OutlineButtonTemplate_Initialize__vl_reflection_description_IValueSubscription;
		friend class ::vl_workflow_global::__vwsnc9_PunkUI_punkui_OutlineButtonTemplateConstructor___vwsn_punkui_OutlineButtonTemplate_Initialize__vl_reflection_description_IValueSubscription;
		friend struct ::vl_workflow_global::__vwsnf29_PunkUI_punkui_OutlineButtonTemplateConstructor___vwsn_punkui_OutlineButtonTemplate_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf30_PunkUI_punkui_OutlineButtonTemplateConstructor___vwsn_punkui_OutlineButtonTemplate_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf31_PunkUI_punkui_OutlineButtonTemplateConstructor___vwsn_punkui_OutlineButtonTemplate_Initialize_;
#ifdef VCZH_DESCRIPTABLEOBJECT_WITH_METADATA
		friend struct ::vl::reflection::description::CustomTypeDescriptorSelector<OutlineButtonTemplate>;
#endif
	private:
		void InitFx();
	public:
		OutlineButtonTemplate();
		void __vwsn_instance_ctor_();
		~OutlineButtonTemplate();

	/* USER_CONTENT_BEGIN(custom members of ::punkui::OutlineButtonTemplate) */
	/* USER_CONTENT_END() */
	};

}
#if defined( _MSC_VER)
#pragma warning(pop)
#elif defined(__clang__)
#pragma clang diagnostic pop
#elif defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

#endif
