/***********************************************************************
!!!!!! DO NOT MODIFY !!!!!!

GacGen.exe Resource.xml

This file is generated by Workflow compiler
https://github.com/vczh-libraries
***********************************************************************/

#ifndef VCZH_WORKFLOW_COMPILER_GENERATED_PRIMARYBUTTONTEMPLATE
#define VCZH_WORKFLOW_COMPILER_GENERATED_PRIMARYBUTTONTEMPLATE

#include "PunkUIPartialClasses.h"

#if defined( _MSC_VER)
#pragma warning(push)
#pragma warning(disable:4250)
#elif defined(__clang__)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wparentheses-equality"
#elif defined(__GNUC__)
#pragma GCC diagnostic push
#endif

namespace punkui
{
	class PrimaryButtonTemplate : public ::vl::presentation::templates::GuiButtonTemplate, public ::punkui::PrimaryButtonTemplateConstructor, public ::vl::reflection::Description<PrimaryButtonTemplate>
	{
		friend class ::punkui::PrimaryButtonTemplateConstructor;
		friend class ::vl_workflow_global::__vwsnc11_PunkUI_punkui_PrimaryButtonTemplateConstructor___vwsn_punkui_PrimaryButtonTemplate_Initialize__vl_reflection_description_IValueSubscription;
		friend class ::vl_workflow_global::__vwsnc12_PunkUI_punkui_PrimaryButtonTemplateConstructor___vwsn_punkui_PrimaryButtonTemplate_Initialize__vl_reflection_description_IValueSubscription;
		friend class ::vl_workflow_global::__vwsnc13_PunkUI_punkui_PrimaryButtonTemplateConstructor___vwsn_punkui_PrimaryButtonTemplate_Initialize__vl_reflection_description_IValueSubscription;
		friend struct ::vl_workflow_global::__vwsnf32_PunkUI_punkui_PrimaryButtonTemplateConstructor___vwsn_punkui_PrimaryButtonTemplate_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf33_PunkUI_punkui_PrimaryButtonTemplateConstructor___vwsn_punkui_PrimaryButtonTemplate_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf34_PunkUI_punkui_PrimaryButtonTemplateConstructor___vwsn_punkui_PrimaryButtonTemplate_Initialize_;
#ifdef VCZH_DESCRIPTABLEOBJECT_WITH_METADATA
		friend struct ::vl::reflection::description::CustomTypeDescriptorSelector<PrimaryButtonTemplate>;
#endif
	private:
		void InitFx();
	public:
		PrimaryButtonTemplate();
		void __vwsn_instance_ctor_();
		~PrimaryButtonTemplate();

	/* USER_CONTENT_BEGIN(custom members of ::punkui::PrimaryButtonTemplate) */
	/* USER_CONTENT_END() */
	};

}
#if defined( _MSC_VER)
#pragma warning(pop)
#elif defined(__clang__)
#pragma clang diagnostic pop
#elif defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

#endif
