/***********************************************************************
!!!!!! DO NOT MODIFY !!!!!!

GacGen.exe Resource.xml

This file is generated by Workflow compiler
https://github.com/vczh-libraries
***********************************************************************/

#ifndef VCZH_WORKFLOW_COMPILER_GENERATED_PUNKUI
#define VCZH_WORKFLOW_COMPILER_GENERATED_PUNKUI

#include "PunkUIPartialClasses.h"
#include "DangerButtonTemplate.h"
#include "DashboardPageTemplate.h"
#include "GhostButtonTemplate.h"
#include "MainWindow.h"
#include "OutlineButtonTemplate.h"
#include "PrimaryButtonTemplate.h"
#include "ShowcasePageTemplate.h"

#endif
