/***********************************************************************
!!!!!! DO NOT MODIFY !!!!!!

GacGen.exe Resource.xml

This file is generated by Workflow compiler
https://github.com/vczh-libraries
***********************************************************************/

#ifndef VCZH_WORKFLOW_COMPILER_GENERATED_PUNKUIREFLECTION
#define VCZH_WORKFLOW_COMPILER_GENERATED_PUNKUIREFLECTION

#include "PunkUI.h"

#if defined( _MSC_VER)
#pragma warning(push)
#pragma warning(disable:4250)
#elif defined(__clang__)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wparentheses-equality"
#elif defined(__GNUC__)
#pragma GCC diagnostic push
#endif

/***********************************************************************
Reflection
***********************************************************************/

namespace vl
{
	namespace reflection
	{
		namespace description
		{
#ifndef VCZH_DEBUG_NO_REFLECTION
			DECL_TYPE_INFO(::punkui::DangerButtonTemplate)
			DECL_TYPE_INFO(::punkui::DangerButtonTemplateConstructor)
			DECL_TYPE_INFO(::punkui::DashboardPageTemplate)
			DECL_TYPE_INFO(::punkui::DashboardPageTemplateConstructor)
			DECL_TYPE_INFO(::punkui::GhostButtonTemplate)
			DECL_TYPE_INFO(::punkui::GhostButtonTemplateConstructor)
			DECL_TYPE_INFO(::punkui::MainWindow)
			DECL_TYPE_INFO(::punkui::MainWindowConstructor)
			DECL_TYPE_INFO(::punkui::NavLinkTemplate)
			DECL_TYPE_INFO(::punkui::NavLinkTemplateConstructor)
			DECL_TYPE_INFO(::punkui::OutlineButtonTemplate)
			DECL_TYPE_INFO(::punkui::OutlineButtonTemplateConstructor)
			DECL_TYPE_INFO(::punkui::PrimaryButtonTemplate)
			DECL_TYPE_INFO(::punkui::PrimaryButtonTemplateConstructor)
			DECL_TYPE_INFO(::punkui::ShowcasePageTemplate)
			DECL_TYPE_INFO(::punkui::ShowcasePageTemplateConstructor)
#endif

			extern bool LoadPunkUITypes();
		}
	}
}

#if defined( _MSC_VER)
#pragma warning(pop)
#elif defined(__clang__)
#pragma clang diagnostic pop
#elif defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

#endif
