/***********************************************************************
!!!!!! DO NOT MODIFY !!!!!!

GacGen.exe Resource.xml

This file is generated by Workflow compiler
https://github.com/vczh-libraries
***********************************************************************/

#include "PunkUI.h"
/* CodePack:BeginIgnore() */
#ifndef VCZH_DEBUG_NO_REFLECTION
/* CodePack:ConditionOff(VCZH_DEBUG_NO_REFLECTION, PunkUIReflection.h) */
#include "PunkUIReflection.h"
#endif
/* CodePack:EndIgnore() */

#if defined( _MSC_VER)
#pragma warning(push)
#pragma warning(disable:4250)
#elif defined(__clang__)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wparentheses-equality"
#elif defined(__GNUC__)
#pragma GCC diagnostic push
#endif

#define GLOBAL_SYMBOL ::vl_workflow_global::PunkUI::
#define GLOBAL_NAME ::vl_workflow_global::PunkUI::Instance().
#define GLOBAL_OBJ &::vl_workflow_global::PunkUI::Instance()

/* USER_CONTENT_BEGIN(custom global declarations) */
namespace punkui {
	static void AttachBadge(PunkPanelStyle style, Color bg, GuiBoundsComposition* face)
	{
		style.background = bg;
		static PunkPanel* panels[16] = {};
		static int next = 0;
		if (next < 16)
		{
			panels[next] = new PunkPanel(style);
			panels[next]->AttachTo(face);
			next++;
		}
	}

	static void AttachPanel(const PunkPanelStyle& style, GuiBoundsComposition* face)
	{
		static PunkPanel* panels[32] = {};
		static int next = 0;
		if (next < 32)
		{
			panels[next] = new PunkPanel(style);
			panels[next]->AttachTo(face);
			next++;
		}
	}
}
/* USER_CONTENT_END() */

/***********************************************************************
Class (::punkui::ShowcasePageTemplate)
***********************************************************************/

namespace punkui
{
	void ShowcasePageTemplate::InstallPunkPanels()
	{/* USER_CONTENT_BEGIN(::punkui::ShowcasePageTemplate) */
		// 徽标：tone 低透明混白底 + 切角 + 墨边 + 2px 投影
		PunkPanelStyle badge = PunkPanelStyle::Badge();
		AttachBadge(badge, Color(0xDA, 0xF7, 0xE4), badge1Face);
		AttachBadge(badge, Color(0xFF, 0xF6, 0xC7), badge2Face);
		AttachBadge(badge, Color(0x15, 0x15, 0x15), badge3Face);
		AttachBadge(badge, Color(0xE8, 0x15, 0x1C), badge4Face);
		AttachBadge(badge, Color(0x15, 0x15, 0x15), badge5Face);
		AttachBadge(badge, Color(0xFB, 0xD5, 0xD6), badge6Face);

		// 卡片：白底半调 + 对角切角 + 墨边 + 6px 投影
		AttachPanel(PunkPanelStyle::Card(), card1Face);
		AttachPanel(PunkPanelStyle::Card(), card2Face);
		AttachPanel(PunkPanelStyle::Card(), card3Face);

		// 提示条：白底半调 + 3px 墨边 + 4px 投影
		AttachPanel(PunkPanelStyle::Alert(), alert1Face);
		AttachPanel(PunkPanelStyle::Alert(), alert2Face);
		AttachPanel(PunkPanelStyle::Alert(), alert3Face);
		AttachPanel(PunkPanelStyle::Alert(), alert4Face);

		// 表格外框：白底 + 3px 墨边 + 6px 投影（无切角无半调）
		PunkPanelStyle table = PunkPanelStyle::Alert();
		table.chamferTopRight = 0;
		table.chamferBottomLeft = 0;
		table.borderWidth = 3;
		table.shadowOffset = 6;
		table.halftone = false;
		AttachPanel(table, tableWrap);
	}/* USER_CONTENT_END() */

	void ShowcasePageTemplate::OpenModal()
	{/* USER_CONTENT_BEGIN(::punkui::ShowcasePageTemplate) */
		if (auto host = GetRelatedControlHost())
		{
			if (auto window = dynamic_cast<::punkui::MainWindow*>(host))
			{
				window->OpenModal();
			}
		}
	}/* USER_CONTENT_END() */

	ShowcasePageTemplate::ShowcasePageTemplate()
	{
		auto __vwsn_resource_ = ::vl::__vwsn::This(::vl::presentation::GetResourceManager())->GetResourceFromClassName(::vl::WString::Unmanaged(L"punkui::ShowcasePageTemplate"));
		auto __vwsn_resolver_ = ::vl::Ptr<::vl::presentation::GuiResourcePathResolver>(new ::vl::presentation::GuiResourcePathResolver(__vwsn_resource_, ::vl::__vwsn::This(__vwsn_resource_.Obj())->GetWorkingDirectory()));
		::vl::__vwsn::This(this)->SetResourceResolver(__vwsn_resolver_);
		::vl::__vwsn::This(this)->__vwsn_punkui_ShowcasePageTemplate_Initialize(this);
		this->__vwsn_instance_ctor_();
	}

	void ShowcasePageTemplate::__vwsn_instance_ctor_()
	{
		::vl::__vwsn::This(this->page)->InstallPunkPanels();
	}

	ShowcasePageTemplate::~ShowcasePageTemplate()
	{
		this->FinalizeInstanceRecursively(static_cast<::vl::presentation::templates::GuiTemplate*>(this));
	}

}
#undef GLOBAL_SYMBOL
#undef GLOBAL_NAME
#undef GLOBAL_OBJ

#if defined( _MSC_VER)
#pragma warning(pop)
#elif defined(__clang__)
#pragma clang diagnostic pop
#elif defined(__GNUC__)
#pragma GCC diagnostic pop
#endif
