/***********************************************************************
!!!!!! DO NOT MODIFY !!!!!!

GacGen.exe Resource.xml

This file is generated by Workflow compiler
https://github.com/vczh-libraries
***********************************************************************/

#ifndef VCZH_WORKFLOW_COMPILER_GENERATED_SHOWCASEPAGETEMPLATE
#define VCZH_WORKFLOW_COMPILER_GENERATED_SHOWCASEPAGETEMPLATE

#include "PunkUIPartialClasses.h"

#if defined( _MSC_VER)
#pragma warning(push)
#pragma warning(disable:4250)
#elif defined(__clang__)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wparentheses-equality"
#elif defined(__GNUC__)
#pragma GCC diagnostic push
#endif

namespace punkui
{
	class ShowcasePageTemplate : public ::vl::presentation::templates::GuiControlTemplate, public ::punkui::ShowcasePageTemplateConstructor, public ::vl::reflection::Description<ShowcasePageTemplate>
	{
		friend class ::punkui::ShowcasePageTemplateConstructor;
		friend struct ::vl_workflow_global::__vwsnf14_PunkUI_punkui_ShowcasePageTemplateConstructor___vwsn_punkui_ShowcasePageTemplate_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf15_PunkUI_punkui_ShowcasePageTemplateConstructor___vwsn_punkui_ShowcasePageTemplate_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf16_PunkUI_punkui_ShowcasePageTemplateConstructor___vwsn_punkui_ShowcasePageTemplate_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf17_PunkUI_punkui_ShowcasePageTemplateConstructor___vwsn_punkui_ShowcasePageTemplate_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf18_PunkUI_punkui_ShowcasePageTemplateConstructor___vwsn_punkui_ShowcasePageTemplate_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf19_PunkUI_punkui_ShowcasePageTemplateConstructor___vwsn_punkui_ShowcasePageTemplate_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf20_PunkUI_punkui_ShowcasePageTemplateConstructor___vwsn_punkui_ShowcasePageTemplate_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf21_PunkUI_punkui_ShowcasePageTemplateConstructor___vwsn_punkui_ShowcasePageTemplate_Initialize_;
#ifdef VCZH_DESCRIPTABLEOBJECT_WITH_METADATA
		friend struct ::vl::reflection::description::CustomTypeDescriptorSelector<ShowcasePageTemplate>;
#endif
	private:
		void InstallPunkPanels();
		void OpenModal();
	public:
		ShowcasePageTemplate();
		void __vwsn_instance_ctor_();
		~ShowcasePageTemplate();

	/* USER_CONTENT_BEGIN(custom members of ::punkui::ShowcasePageTemplate) */
	/* USER_CONTENT_END() */
	};

}
#if defined( _MSC_VER)
#pragma warning(pop)
#elif defined(__clang__)
#pragma clang diagnostic pop
#elif defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

#endif
