/***********************************************************************
!!!!!! DO NOT MODIFY !!!!!!

GacGen.exe Resource.xml

This file is generated by Workflow compiler
https://github.com/vczh-libraries
***********************************************************************/

#include "PunkSkin.h"
/* CodePack:BeginIgnore() */
#ifndef VCZH_DEBUG_NO_REFLECTION
/* CodePack:ConditionOff(VCZH_DEBUG_NO_REFLECTION, PunkSkinReflection.h) */
#include "PunkSkinReflection.h"
#endif
/* CodePack:EndIgnore() */

#if defined( _MSC_VER)
#pragma warning(push)
#pragma warning(disable:4250)
#elif defined(__clang__)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wparentheses-equality"
#elif defined(__GNUC__)
#pragma GCC diagnostic push
#endif

#define GLOBAL_SYMBOL ::vl_workflow_global::PunkSkin::
#define GLOBAL_NAME ::vl_workflow_global::PunkSkin::Instance().
#define GLOBAL_OBJ &::vl_workflow_global::PunkSkin::Instance()

/* USER_CONTENT_BEGIN(custom global declarations) */
#include "../../PunkElements/PunkFx.h"
/* USER_CONTENT_END() */

/***********************************************************************
Class (::punkskin::CheckBoxTemplate)
***********************************************************************/

namespace punkskin
{
	void CheckBoxTemplate::InitFx()
	{/* USER_CONTENT_BEGIN(::punkskin::CheckBoxTemplate) */
		// UILIB UiSwitch：圆钮 translateX 5 -> 25（punk 3px 边框下的几何结果），轨道 #000 -> #E8151C
		auto thumbFx = punkfx::GetFxSlot<punkfx::SlideDriver>(this, L"PunkFx.SwitchThumb");
		thumbFx->Bind(this->thumb, 5);
		thumbFx->SetNow(this->GetSelected() ? 25.0 : 5.0);

		auto trackFx = punkfx::GetFxSlot<punkfx::ColorDriver>(this, L"PunkFx.SwitchTrack");
		if (auto trackElement = this->trackBg->GetOwnedElement().Cast<::vl::presentation::elements::GuiSolidBackgroundElement>())
		{
			trackFx->Bind(trackElement, punkfx::SwitchTrackColor(this->GetSelected(), this->GetVisuallyEnabled()));
		}

		auto applySwitchState = [this, thumbFx, trackFx]()
		{
			bool selected = this->GetSelected();
			bool enabled = this->GetVisuallyEnabled();
			if (this->GetRelatedControlHost())
			{
				thumbFx->TweenTo(this, selected ? 25.0 : 5.0);
				trackFx->TweenTo(this, punkfx::SwitchTrackColor(selected, enabled));
			}
			else
			{
				// 尚未进入窗口树：此时期入队的动画会停在 pending 永不启动，
				// 且初始状态本就无需过渡（UILIB 的 transition 同样只动画状态变化），直写终态
				thumbFx->SetNow(selected ? 25.0 : 5.0);
				trackFx->SetNow(punkfx::SwitchTrackColor(selected, enabled));
			}
		};
		::vl::__vwsn::EventAttach(this->SelectedChanged, ::vl::Func<void(::vl::presentation::compositions::GuiGraphicsComposition*, ::vl::presentation::compositions::GuiEventArgs*)>(
			[applySwitchState](::vl::presentation::compositions::GuiGraphicsComposition* sender, ::vl::presentation::compositions::GuiEventArgs* arguments)
			{
				applySwitchState();
			}));
		::vl::__vwsn::EventAttach(this->VisuallyEnabledChanged, ::vl::Func<void(::vl::presentation::compositions::GuiGraphicsComposition*, ::vl::presentation::compositions::GuiEventArgs*)>(
			[applySwitchState](::vl::presentation::compositions::GuiGraphicsComposition* sender, ::vl::presentation::compositions::GuiEventArgs* arguments)
			{
				applySwitchState();
			}));
	}/* USER_CONTENT_END() */

	CheckBoxTemplate::CheckBoxTemplate()
	{
		auto __vwsn_resource_ = ::vl::__vwsn::This(::vl::presentation::GetResourceManager())->GetResourceFromClassName(::vl::WString::Unmanaged(L"punkskin::CheckBoxTemplate"));
		auto __vwsn_resolver_ = ::vl::Ptr<::vl::presentation::GuiResourcePathResolver>(new ::vl::presentation::GuiResourcePathResolver(__vwsn_resource_, ::vl::__vwsn::This(__vwsn_resource_.Obj())->GetWorkingDirectory()));
		::vl::__vwsn::This(this)->SetResourceResolver(__vwsn_resolver_);
		::vl::__vwsn::This(this)->__vwsn_punkskin_CheckBoxTemplate_Initialize(this);
		this->__vwsn_instance_ctor_();
	}

	void CheckBoxTemplate::__vwsn_instance_ctor_()
	{
		::vl::__vwsn::This(this->self)->InitFx();
	}

	CheckBoxTemplate::~CheckBoxTemplate()
	{
		this->FinalizeInstanceRecursively(static_cast<::vl::presentation::templates::GuiTemplate*>(this));
	}

}
#undef GLOBAL_SYMBOL
#undef GLOBAL_NAME
#undef GLOBAL_OBJ

#if defined( _MSC_VER)
#pragma warning(pop)
#elif defined(__clang__)
#pragma clang diagnostic pop
#elif defined(__GNUC__)
#pragma GCC diagnostic pop
#endif
