/***********************************************************************
!!!!!! DO NOT MODIFY !!!!!!

GacGen.exe Resource.xml

This file is generated by Workflow compiler
https://github.com/vczh-libraries
***********************************************************************/

#ifndef VCZH_WORKFLOW_COMPILER_GENERATED_CHECKBOXTEMPLATE
#define VCZH_WORKFLOW_COMPILER_GENERATED_CHECKBOXTEMPLATE

#include "PunkSkinPartialClasses.h"

#if defined( _MSC_VER)
#pragma warning(push)
#pragma warning(disable:4250)
#elif defined(__clang__)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wparentheses-equality"
#elif defined(__GNUC__)
#pragma GCC diagnostic push
#endif

namespace punkskin
{
	class CheckBoxTemplate : public ::vl::presentation::templates::GuiSelectableButtonTemplate, public ::punkskin::CheckBoxTemplateConstructor, public ::vl::reflection::Description<CheckBoxTemplate>
	{
		friend class ::punkskin::CheckBoxTemplateConstructor;
		friend class ::vl_workflow_global::__vwsnc4_PunkSkin_punkskin_CheckBoxTemplateConstructor___vwsn_punkskin_CheckBoxTemplate_Initialize__vl_reflection_description_IValueSubscription;
		friend class ::vl_workflow_global::__vwsnc5_PunkSkin_punkskin_CheckBoxTemplateConstructor___vwsn_punkskin_CheckBoxTemplate_Initialize__vl_reflection_description_IValueSubscription;
		friend class ::vl_workflow_global::__vwsnc6_PunkSkin_punkskin_CheckBoxTemplateConstructor___vwsn_punkskin_CheckBoxTemplate_Initialize__vl_reflection_description_IValueSubscription;
		friend class ::vl_workflow_global::__vwsnc7_PunkSkin_punkskin_CheckBoxTemplateConstructor___vwsn_punkskin_CheckBoxTemplate_Initialize__vl_reflection_description_IValueSubscription;
		friend struct ::vl_workflow_global::__vwsnf17_PunkSkin_punkskin_CheckBoxTemplateConstructor___vwsn_punkskin_CheckBoxTemplate_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf18_PunkSkin_punkskin_CheckBoxTemplateConstructor___vwsn_punkskin_CheckBoxTemplate_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf19_PunkSkin_punkskin_CheckBoxTemplateConstructor___vwsn_punkskin_CheckBoxTemplate_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf20_PunkSkin_punkskin_CheckBoxTemplateConstructor___vwsn_punkskin_CheckBoxTemplate_Initialize_;
#ifdef VCZH_DESCRIPTABLEOBJECT_WITH_METADATA
		friend struct ::vl::reflection::description::CustomTypeDescriptorSelector<CheckBoxTemplate>;
#endif
	private:
		void InitFx();
	public:
		CheckBoxTemplate();
		void __vwsn_instance_ctor_();
		~CheckBoxTemplate();

	/* USER_CONTENT_BEGIN(custom members of ::punkskin::CheckBoxTemplate) */
	/* USER_CONTENT_END() */
	};

}
#if defined( _MSC_VER)
#pragma warning(pop)
#elif defined(__clang__)
#pragma clang diagnostic pop
#elif defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

#endif
