/***********************************************************************
!!!!!! DO NOT MODIFY !!!!!!

GacGen.exe Resource.xml

This file is generated by Workflow compiler
https://github.com/vczh-libraries
***********************************************************************/

#ifndef VCZH_WORKFLOW_COMPILER_GENERATED_DOCUMENTTEXTBOXTEMPLATE
#define VCZH_WORKFLOW_COMPILER_GENERATED_DOCUMENTTEXTBOXTEMPLATE

#include "PunkSkinPartialClasses.h"

#if defined( _MSC_VER)
#pragma warning(push)
#pragma warning(disable:4250)
#elif defined(__clang__)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wparentheses-equality"
#elif defined(__GNUC__)
#pragma GCC diagnostic push
#endif

namespace punkskin
{
	class DocumentTextBoxTemplate : public ::vl::presentation::templates::GuiDocumentLabelTemplate, public ::punkskin::DocumentTextBoxTemplateConstructor, public ::vl::reflection::Description<DocumentTextBoxTemplate>
	{
		friend class ::punkskin::DocumentTextBoxTemplateConstructor;
#ifdef VCZH_DESCRIPTABLEOBJECT_WITH_METADATA
		friend struct ::vl::reflection::description::CustomTypeDescriptorSelector<DocumentTextBoxTemplate>;
#endif
	private:
		void InitFx();
	public:
		DocumentTextBoxTemplate();
		void __vwsn_instance_ctor_();
		~DocumentTextBoxTemplate();

	/* USER_CONTENT_BEGIN(custom members of ::punkskin::DocumentTextBoxTemplate) */
	/* USER_CONTENT_END() */
	};

}
#if defined( _MSC_VER)
#pragma warning(pop)
#elif defined(__clang__)
#pragma clang diagnostic pop
#elif defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

#endif
