/***********************************************************************
!!!!!! DO NOT MODIFY !!!!!!

GacGen.exe Resource.xml

This file is generated by Workflow compiler
https://github.com/vczh-libraries
***********************************************************************/

#include "PunkSkin.h"
/* CodePack:BeginIgnore() */
#ifndef VCZH_DEBUG_NO_REFLECTION
/* CodePack:ConditionOff(VCZH_DEBUG_NO_REFLECTION, PunkSkinReflection.h) */
#include "PunkSkinReflection.h"
#endif
/* CodePack:EndIgnore() */

#if defined( _MSC_VER)
#pragma warning(push)
#pragma warning(disable:4250)
#elif defined(__clang__)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wparentheses-equality"
#elif defined(__GNUC__)
#pragma GCC diagnostic push
#endif

#define GLOBAL_SYMBOL ::vl_workflow_global::PunkSkin::
#define GLOBAL_NAME ::vl_workflow_global::PunkSkin::Instance().
#define GLOBAL_OBJ &::vl_workflow_global::PunkSkin::Instance()

/* USER_CONTENT_BEGIN(custom global declarations) */
#include "../../PunkElements/PunkFx.h"
/* USER_CONTENT_END() */

/***********************************************************************
Class (::punkskin::DocumentTextBoxTemplate)
***********************************************************************/

namespace punkskin
{
	void DocumentTextBoxTemplate::InitFx()
	{/* USER_CONTENT_BEGIN(::punkskin::DocumentTextBoxTemplate) */
		// punk 规格：输入框聚焦投影 #000 -> #E8151C（边框保持黑）
		auto shadowFx = punkfx::GetFxSlot<punkfx::ColorDriver>(this, L"PunkFx.InputShadow");
		if (auto shadowElement = this->shadowBounds->GetOwnedElement().Cast<::vl::presentation::elements::GuiSolidBackgroundElement>())
		{
			shadowFx->Bind(shadowElement, punkfx::InputShadowColor(this->GetFocused()));
		}
		::vl::__vwsn::EventAttach(this->FocusedChanged, ::vl::Func<void(::vl::presentation::compositions::GuiGraphicsComposition*, ::vl::presentation::compositions::GuiEventArgs*)>(
			[this, shadowFx](::vl::presentation::compositions::GuiGraphicsComposition* sender, ::vl::presentation::compositions::GuiEventArgs* arguments)
			{
				shadowFx->TweenTo(this, punkfx::InputShadowColor(this->GetFocused()));
			}));
	}/* USER_CONTENT_END() */

	DocumentTextBoxTemplate::DocumentTextBoxTemplate()
	{
		auto __vwsn_resource_ = ::vl::__vwsn::This(::vl::presentation::GetResourceManager())->GetResourceFromClassName(::vl::WString::Unmanaged(L"punkskin::DocumentTextBoxTemplate"));
		auto __vwsn_resolver_ = ::vl::Ptr<::vl::presentation::GuiResourcePathResolver>(new ::vl::presentation::GuiResourcePathResolver(__vwsn_resource_, ::vl::__vwsn::This(__vwsn_resource_.Obj())->GetWorkingDirectory()));
		::vl::__vwsn::This(this)->SetResourceResolver(__vwsn_resolver_);
		::vl::__vwsn::This(this)->__vwsn_punkskin_DocumentTextBoxTemplate_Initialize(this);
		this->__vwsn_instance_ctor_();
	}

	void DocumentTextBoxTemplate::__vwsn_instance_ctor_()
	{
		::vl::__vwsn::This(this->self)->InitFx();
	}

	DocumentTextBoxTemplate::~DocumentTextBoxTemplate()
	{
		this->FinalizeInstanceRecursively(static_cast<::vl::presentation::templates::GuiTemplate*>(this));
	}

}
#undef GLOBAL_SYMBOL
#undef GLOBAL_NAME
#undef GLOBAL_OBJ

#if defined( _MSC_VER)
#pragma warning(pop)
#elif defined(__clang__)
#pragma clang diagnostic pop
#elif defined(__GNUC__)
#pragma GCC diagnostic pop
#endif
