/***********************************************************************
!!!!!! DO NOT MODIFY !!!!!!

GacGen.exe Resource.xml

This file is generated by Workflow compiler
https://github.com/vczh-libraries
***********************************************************************/

#ifndef VCZH_WORKFLOW_COMPILER_GENERATED_DOCUMENTVIEWERTEMPLATE
#define VCZH_WORKFLOW_COMPILER_GENERATED_DOCUMENTVIEWERTEMPLATE

#include "PunkSkinPartialClasses.h"

#if defined( _MSC_VER)
#pragma warning(push)
#pragma warning(disable:4250)
#elif defined(__clang__)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wparentheses-equality"
#elif defined(__GNUC__)
#pragma GCC diagnostic push
#endif

namespace punkskin
{
	class DocumentViewerTemplate : public ::vl::presentation::templates::GuiDocumentViewerTemplate, public ::punkskin::DocumentViewerTemplateConstructor, public ::vl::reflection::Description<DocumentViewerTemplate>
	{
		friend class ::punkskin::DocumentViewerTemplateConstructor;
		friend struct ::vl_workflow_global::__vwsnf21_PunkSkin_punkskin_DocumentViewerTemplateConstructor___vwsn_punkskin_DocumentViewerTemplate_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf22_PunkSkin_punkskin_DocumentViewerTemplateConstructor___vwsn_punkskin_DocumentViewerTemplate_Initialize_;
#ifdef VCZH_DESCRIPTABLEOBJECT_WITH_METADATA
		friend struct ::vl::reflection::description::CustomTypeDescriptorSelector<DocumentViewerTemplate>;
#endif
	private:
		void InitFx();
	public:
		DocumentViewerTemplate();
		void __vwsn_instance_ctor_();
		~DocumentViewerTemplate();

	/* USER_CONTENT_BEGIN(custom members of ::punkskin::DocumentViewerTemplate) */
	/* USER_CONTENT_END() */
	};

}
#if defined( _MSC_VER)
#pragma warning(pop)
#elif defined(__clang__)
#pragma clang diagnostic pop
#elif defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

#endif
