/***********************************************************************
!!!!!! DO NOT MODIFY !!!!!!

GacGen.exe Resource.xml

This file is generated by Workflow compiler
https://github.com/vczh-libraries
***********************************************************************/

#ifndef VCZH_WORKFLOW_COMPILER_GENERATED_PUNKSKIN
#define VCZH_WORKFLOW_COMPILER_GENERATED_PUNKSKIN

#include "PunkSkinPartialClasses.h"

#endif
