/***********************************************************************
!!!!!! DO NOT MODIFY !!!!!!

GacGen.exe Resource.xml

This file is generated by Workflow compiler
https://github.com/vczh-libraries
***********************************************************************/

#ifndef VCZH_WORKFLOW_COMPILER_GENERATED_PUNKSKINREFLECTION
#define VCZH_WORKFLOW_COMPILER_GENERATED_PUNKSKINREFLECTION

#include "PunkSkin.h"

#if defined( _MSC_VER)
#pragma warning(push)
#pragma warning(disable:4250)
#elif defined(__clang__)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wparentheses-equality"
#elif defined(__GNUC__)
#pragma GCC diagnostic push
#endif

/***********************************************************************
Reflection
***********************************************************************/

namespace vl
{
	namespace reflection
	{
		namespace description
		{
#ifndef VCZH_DEBUG_NO_REFLECTION
			DECL_TYPE_INFO(::punkskin::ButtonTemplate)
			DECL_TYPE_INFO(::punkskin::ButtonTemplateConstructor)
			DECL_TYPE_INFO(::punkskin::CheckBoxTemplate)
			DECL_TYPE_INFO(::punkskin::CheckBoxTemplateConstructor)
			DECL_TYPE_INFO(::punkskin::CustomControlTemplate)
			DECL_TYPE_INFO(::punkskin::CustomControlTemplateConstructor)
			DECL_TYPE_INFO(::punkskin::CustomFrameWindowTemplate)
			DECL_TYPE_INFO(::punkskin::CustomFrameWindowTemplateConstructor)
			DECL_TYPE_INFO(::punkskin::DocumentLabelTemplate)
			DECL_TYPE_INFO(::punkskin::DocumentLabelTemplateConstructor)
			DECL_TYPE_INFO(::punkskin::DocumentTextBoxTemplate)
			DECL_TYPE_INFO(::punkskin::DocumentTextBoxTemplateConstructor)
			DECL_TYPE_INFO(::punkskin::DocumentViewerTemplate)
			DECL_TYPE_INFO(::punkskin::DocumentViewerTemplateConstructor)
			DECL_TYPE_INFO(::punkskin::HScrollHandleTemplate)
			DECL_TYPE_INFO(::punkskin::HScrollHandleTemplateConstructor)
			DECL_TYPE_INFO(::punkskin::HScrollTemplate)
			DECL_TYPE_INFO(::punkskin::HScrollTemplateConstructor)
			DECL_TYPE_INFO(::punkskin::LabelTemplate)
			DECL_TYPE_INFO(::punkskin::LabelTemplateConstructor)
			DECL_TYPE_INFO(::punkskin::ProgressBarTemplate)
			DECL_TYPE_INFO(::punkskin::ProgressBarTemplateConstructor)
			DECL_TYPE_INFO(::punkskin::ScrollButtonTemplate)
			DECL_TYPE_INFO(::punkskin::ScrollButtonTemplateConstructor)
			DECL_TYPE_INFO(::punkskin::ScrollViewTemplate)
			DECL_TYPE_INFO(::punkskin::ScrollViewTemplateConstructor)
			DECL_TYPE_INFO(::punkskin::Theme)
			DECL_TYPE_INFO(::punkskin::ThemeConstructor)
			DECL_TYPE_INFO(::punkskin::TitleBarButtonTemplate)
			DECL_TYPE_INFO(::punkskin::TitleBarButtonTemplateConstructor)
			DECL_TYPE_INFO(::punkskin::TitleBarCloseButtonTemplate)
			DECL_TYPE_INFO(::punkskin::TitleBarCloseButtonTemplateConstructor)
			DECL_TYPE_INFO(::punkskin::TooltipTemplate)
			DECL_TYPE_INFO(::punkskin::TooltipTemplateConstructor)
			DECL_TYPE_INFO(::punkskin::VScrollHandleTemplate)
			DECL_TYPE_INFO(::punkskin::VScrollHandleTemplateConstructor)
			DECL_TYPE_INFO(::punkskin::VScrollTemplate)
			DECL_TYPE_INFO(::punkskin::VScrollTemplateConstructor)
#endif

			extern bool LoadPunkSkinTypes();
		}
	}
}

#if defined( _MSC_VER)
#pragma warning(pop)
#elif defined(__clang__)
#pragma clang diagnostic pop
#elif defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

#endif
